export const EDITOR_MAXIMISED = 'EDITOR_MAXIMISED';
export const EDITOR_MINIMISED = 'EDITOR_MINIMISED';
export const PREVIEWER_MAXIMISED = 'PREVIEWER_MAXIMISED';
export const PREVIEWER_MINIMISED = 'PREVIEWER_MINIMISED';
export const SET_MARKDOWN   = 'SET_MARKDOWN';
